# Generated by Django 2.2.7 on 2020-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息管理',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='书名')),
                ('page', models.IntegerField(verbose_name='页数')),
            ],
            options={
                'verbose_name': '书本信息',
                'verbose_name_plural': '书本信息管理',
            },
        ),
    ]
