# Generated by Django 2.2.7 on 2020-03-03 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100, unique=True, verbose_name='活动名')),
                ('activity_descripation', models.TextField(blank=True, verbose_name='活动描述')),
                ('activity_start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='活动开始时间')),
                ('activity_end_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='活动结束时间')),
                ('activity_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity_operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': '活动信息表',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=16, unique=True, verbose_name='活动类型')),
            ],
            options={
                'verbose_name': 'ActivityType',
                'verbose_name_plural': '活动类型表',
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='行政编号')),
                ('name', models.CharField(max_length=20, verbose_name='行政区划名')),
                ('parent_id', models.CharField(max_length=20, verbose_name='上级行政编号')),
                ('type', models.IntegerField(default=0, verbose_name='行政等级')),
            ],
            options={
                'verbose_name': 'Areas',
                'verbose_name_plural': '行政区划表',
                'db_table': 'wechatapp',
            },
        ),
        migrations.CreateModel(
            name='ProductBaseInfo',
            fields=[
                ('productId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='货号')),
                ('productName', models.CharField(max_length=255, verbose_name='商品名称')),
                ('systemCode', models.BigIntegerField(blank=True)),
                ('barCode', models.BigIntegerField(blank=True)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('norms', models.CharField(blank=True, max_length=255)),
                ('weight', models.IntegerField(blank=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('brief', models.TextField(blank=True, default='这里是商品简介')),
                ('brand', models.TextField(blank=True, default='这里是商品牌')),
                ('smallurl', stdimage.models.StdImageField(default='', upload_to='ProductPreViewPic', verbose_name='商品展示缩略图')),
                ('shell', models.CharField(choices=[('on', '上架'), ('off', '下架')], default='on', max_length=3)),
                ('quantity', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name': '商品详情管理',
                'verbose_name_plural': '商品详情管理',
            },
        ),
        migrations.CreateModel(
            name='ProductMainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50, verbose_name='商品总类')),
            ],
            options={
                'verbose_name': '商品总类注册',
                'verbose_name_plural': '商品总类注册',
            },
        ),
        migrations.CreateModel(
            name='ProductSecondCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeChildName', models.CharField(max_length=50, verbose_name='商品大类')),
                ('url', stdimage.models.StdImageField(default='', upload_to='typea', verbose_name='大类缩略图')),
                ('typeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.ProductMainCategory')),
            ],
            options={
                'verbose_name': '商品大类注册',
                'verbose_name_plural': '商品大类注册',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True, verbose_name='门店名')),
                ('store_address', models.TextField(blank=True, verbose_name='门店地址')),
                ('store_area', models.CharField(blank=True, max_length=100, verbose_name='门店商区')),
                ('store_telephone', models.CharField(blank=True, max_length=100, verbose_name='门店电话')),
                ('store_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='门店经度')),
                ('store_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='门店纬度')),
                ('store_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('store_operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': '门店信息表',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('productbaseinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wechatapp.ProductBaseInfo')),
                ('tag', models.CharField(choices=[('h', '热门商品'), ('d', '降价促销'), ('n', '新品上架')], max_length=1)),
            ],
            options={
                'verbose_name': '商品标签管理',
                'verbose_name_plural': '商品标签管理',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='unionid')),
                ('nickName', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('avatarUrl', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='头像')),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户微信id')),
            ],
            options={
                'verbose_name': '用户微信注册信息详情',
                'verbose_name_plural': '用户微信注册信息详情',
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_name', models.CharField(blank=True, max_length=128, verbose_name='报名人姓名')),
                ('signup_phone', models.CharField(blank=True, max_length=128, verbose_name='报名人电话')),
                ('signup_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('signup_operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Activity')),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SignUp',
                'verbose_name_plural': '报名信息表',
            },
        ),
        migrations.CreateModel(
            name='ProductUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', stdimage.models.StdImageField(default='', upload_to='img', verbose_name='商品详情轮播图')),
                ('productbaseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='wechatapp.ProductBaseInfo')),
            ],
            options={
                'verbose_name': '商品图片管理',
                'verbose_name_plural': '商品图片管理',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeChildsName', models.CharField(default='子类产品', max_length=50, verbose_name='商品子类')),
                ('url', stdimage.models.StdImageField(default='', upload_to='typeb', verbose_name='子类缩略图')),
                ('typeChildName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.ProductSecondCategory')),
            ],
            options={
                'verbose_name': '商品类别管理',
                'verbose_name_plural': '商品类别管理',
            },
        ),
        migrations.AddField(
            model_name='productbaseinfo',
            name='productType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.ProductType'),
        ),
        migrations.CreateModel(
            name='MyTrolly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=1)),
                ('checkbox', models.IntegerField(choices=[(0, '未选中'), (1, '选中')], default=0)),
                ('productbaseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='wechatapp.ProductBaseInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='wechatapp.UserProfile')),
            ],
            options={
                'verbose_name': '购物车管理',
                'verbose_name_plural': '购物车管理',
            },
        ),
        migrations.CreateModel(
            name='AdvPicModel',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False, verbose_name='序号')),
                ('url', stdimage.models.StdImageField(default='', upload_to='adv', verbose_name='首页广告轮播图')),
                ('productbaseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='wechatapp.ProductBaseInfo')),
            ],
            options={
                'verbose_name': '广告轮播管理',
                'verbose_name_plural': '广告轮播管理',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='联系人')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='详细地址')),
                ('is_default', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='默认设置')),
                ('signup_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('signup_operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='wechatapp.Areas')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='wechatapp.Areas')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='wechatapp.Areas')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': '收件地址信息表',
            },
        ),
        migrations.CreateModel(
            name='ActivityText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文本标题')),
                ('text', models.TextField(blank=True, verbose_name='文本正文')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_text', to='wechatapp.Activity')),
            ],
            options={
                'verbose_name': 'ActivityText',
                'verbose_name_plural': '活动文本表',
            },
        ),
        migrations.CreateModel(
            name='ActivityStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Activity')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Store')),
            ],
            options={
                'verbose_name': 'ActivityStore',
                'verbose_name_plural': '活动门店关联表',
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=250, verbose_name='活动图片')),
                ('image_type', models.IntegerField(choices=[(1, 'type1'), (2, 'type2'), (3, 'type3')], default=1, verbose_name='图片类型')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_image', to='wechatapp.Activity')),
            ],
            options={
                'verbose_name': 'ActivityImage',
                'verbose_name_plural': '活动图片表',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_store',
            field=models.ManyToManyField(related_name='activity_store', through='wechatapp.ActivityStore', to='wechatapp.Store'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='super_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Activity'),
        ),
    ]
