# Generated by Django 2.2.7 on 2020-03-06 22:24

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsecondcategory',
            name='banner_name',
            field=models.CharField(default='', max_length=50, verbose_name='大类广告名称'),
        ),
        migrations.AddField(
            model_name='productsecondcategory',
            name='banner_url',
            field=stdimage.models.StdImageField(default='', upload_to='typeadv', verbose_name='大类广告'),
        ),
    ]
