# Generated by Django 2.2.7 on 2020-03-07 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='手机号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Test')),
            ],
            options={
                'verbose_name': 'Test2',
                'verbose_name_plural': '测试用例2',
            },
        ),
    ]
