# Generated by Django 2.2.7 on 2020-02-17 20:55

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0004_auto_20200217_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='producturl',
            name='url2',
            field=stdimage.models.StdImageField(default='', upload_to='img'),
        ),
    ]
