# Generated by Django 2.2.7 on 2020-03-07 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0004_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test2', to='wechatapp.Test'),
        ),
    ]
