# Generated by Django 2.2.7 on 2020-02-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0005_producturl_url2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producturl',
            name='url2',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
