# Generated by Django 2.2.7 on 2020-03-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0005_auto_20200307_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='类别名')),
                ('desc', models.CharField(max_length=100, verbose_name='类别描述')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': '测试用例3',
            },
        ),
    ]
