# Generated by Django 2.2.7 on 2020-02-18 20:36

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0006_auto_20200217_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbaseinfo',
            name='smallurl',
            field=stdimage.models.StdImageField(default='', upload_to='ProductPreViewPic', verbose_name='商品展示缩略图'),
        ),
        migrations.AlterField(
            model_name='producturl',
            name='url2',
            field=stdimage.models.StdImageField(default='', upload_to='img'),
        ),
    ]
