# Generated by Django 2.2.7 on 2020-02-18 21:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0007_auto_20200218_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producturl',
            name='url2',
        ),
        migrations.AlterField(
            model_name='producturl',
            name='url',
            field=stdimage.models.StdImageField(default='', upload_to='img', verbose_name='商品详情轮播图'),
        ),
    ]
