# Generated by Django 2.2.7 on 2020-03-07 17:19

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0007_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='type_description',
            field=models.CharField(max_length=100, null=True, verbose_name='类型描述'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.ActivityType', verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='super_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Activity', verbose_name='父活动'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=stdimage.models.StdImageField(default='', upload_to='ActivityPoster', verbose_name='活动图片'),
        ),
    ]
