# Generated by Django 2.2.7 on 2020-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0008_auto_20200218_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='tag',
            field=models.CharField(choices=[('h', '热门商品'), ('d', '降价促销'), ('n', '新品上架')], max_length=1),
        ),
    ]
