# Generated by Django 2.2.7 on 2020-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0008_auto_20200307_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimage',
            name='image_description',
            field=models.CharField(max_length=100, null=True, verbose_name='图片描述'),
        ),
    ]
