# Generated by Django 2.2.7 on 2020-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0010_auto_20200307_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_store',
            field=models.ManyToManyField(through='wechatapp.ActivityStore', to='wechatapp.Store', verbose_name='活动门店'),
        ),
        migrations.CreateModel(
            name='Test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, verbose_name='昵称')),
                ('user', models.ManyToManyField(to='wechatapp.Test')),
            ],
            options={
                'verbose_name': 'Test3',
                'verbose_name_plural': '测试用例4',
            },
        ),
    ]
