# Generated by Django 2.2.7 on 2020-02-24 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechatapp', '0010_auto_20200222_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvPicModel',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False, verbose_name='序号')),
                ('url', stdimage.models.StdImageField(default='', upload_to='adv', verbose_name='首页广告轮播图')),
                ('productbaseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='wechatapp.ProductBaseInfo')),
            ],
            options={
                'verbose_name': '商品图片管理',
                'verbose_name_plural': '商品图片管理',
                'ordering': ['order'],
            },
        ),
    ]
