# Generated by Django 2.2.7 on 2020-02-24 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechatapp', '0011_auto_20200224_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_name', models.CharField(blank=True, max_length=128, verbose_name='报名人姓名')),
                ('signup_phone', models.CharField(blank=True, max_length=128, verbose_name='报名人电话')),
                ('signup_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('signup_operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Activity')),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SignUp',
                'verbose_name_plural': '报名信息表',
            },
        ),
    ]
