# Generated by Django 2.2.7 on 2020-03-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0011_auto_20200307_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, verbose_name='权限')),
            ],
            options={
                'verbose_name': 'Test4',
                'verbose_name_plural': '测试用例5',
            },
        ),
        migrations.AlterField(
            model_name='test3',
            name='name',
            field=models.CharField(max_length=13, verbose_name='分组'),
        ),
        migrations.CreateModel(
            name='Test41',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Test4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Test')),
            ],
            options={
                'verbose_name': 'Test41',
                'verbose_name_plural': '测试用例5-1',
            },
        ),
        migrations.AddField(
            model_name='test4',
            name='user',
            field=models.ManyToManyField(through='wechatapp.Test41', to='wechatapp.Test'),
        ),
    ]
