# Generated by Django 2.2.7 on 2020-02-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0012_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advpicmodel',
            options={'ordering': ['order'], 'verbose_name': '广告轮播管理', 'verbose_name_plural': '广告轮播管理'},
        ),
    ]
