# Generated by Django 2.2.7 on 2020-03-01 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechatapp', '0013_auto_20200227_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='行政编号')),
                ('name', models.CharField(max_length=20, verbose_name='行政区划名')),
                ('parent_id', models.CharField(max_length=20, verbose_name='上级行政编号')),
                ('type', models.IntegerField(default=0, verbose_name='行政等级')),
            ],
            options={
                'verbose_name': 'Areas',
                'verbose_name_plural': '行政区划表',
                'db_table': 'wechatapp',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='联系人')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='详细地址')),
                ('is_default', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='默认设置')),
                ('signup_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('signup_operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='wechatapp.Areas')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='wechatapp.Areas')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='wechatapp.Areas')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': '收件地址信息表',
            },
        ),
    ]
