# Generated by Django 2.2.7 on 2020-03-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0014_auto_20200307_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_store',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_store',
            field=models.ManyToManyField(
                to='wechatapp.Store', verbose_name='活动门店'),
        ),
        migrations.DeleteModel(
            name='ActivityStore',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
