# Generated by Django 2.2.7 on 2020-03-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0014_address_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='默认设置'),
        ),
    ]
