# Generated by Django 2.2.7 on 2020-03-08 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0015_auto_20200307_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': '活动信息管理'},
        ),
        migrations.AlterModelOptions(
            name='activityimage',
            options={'verbose_name': 'ActivityImage', 'verbose_name_plural': '活动图片'},
        ),
        migrations.AlterModelOptions(
            name='activitytext',
            options={'verbose_name': 'ActivityText', 'verbose_name_plural': '活动文本'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': 'ActivityType', 'verbose_name_plural': '活动类型管理'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'SignUp', 'verbose_name_plural': '报名信息查看'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': '门店信息管理'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_store',
            field=models.ManyToManyField(blank=True, null=True, to='wechatapp.Store', verbose_name='活动门店'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='barCode',
            field=models.BigIntegerField(blank=True, verbose_name='条形编码'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='brand',
            field=models.TextField(blank=True, default='这里是商品牌', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='brief',
            field=models.TextField(blank=True, default='这里是商品简介', verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='color',
            field=models.CharField(blank=True, max_length=255, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='norms',
            field=models.CharField(blank=True, max_length=255, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='productType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.ProductType', verbose_name='商品分类'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='quantity',
            field=models.IntegerField(blank=True, default=500),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='shell',
            field=models.CharField(choices=[('on', '上架'), ('off', '下架')], default='on', max_length=3, verbose_name='货架'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='smallurl',
            field=stdimage.models.StdImageField(blank=True, default='', null=True, upload_to='ProductPreViewPic', verbose_name='商品展示缩略图'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='systemCode',
            field=models.BigIntegerField(blank=True, verbose_name='系统编码'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='weight',
            field=models.IntegerField(blank=True, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Activity', verbose_name='报名活动'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='signup_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='参加者姓名'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='signup_phone',
            field=models.CharField(blank=True, max_length=128, verbose_name='参加者电话'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.Store', verbose_name='活动门店'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报名用户'),
        ),
    ]
