# Generated by Django 2.2.7 on 2020-03-08 01:44

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0016_auto_20200308_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='type_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类型描述'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='quantity',
            field=models.IntegerField(blank=True, default=500, verbose_name='虚拟库存'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='smallurl',
            field=stdimage.models.StdImageField(blank=True, upload_to='ProductPreViewPic', verbose_name='商品展示缩略图'),
        ),
        migrations.CreateModel(
            name='PTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签名称')),
                ('description', models.CharField(max_length=100, verbose_name='标签描述')),
                ('product', models.ManyToManyField(blank=True, null=True, related_name='product_tag', to='wechatapp.ProductBaseInfo', verbose_name='标注商品')),
            ],
            options={
                'verbose_name': '商品标签管理*',
                'verbose_name_plural': '商品标签管理*',
            },
        ),
    ]
