# Generated by Django 2.2.7 on 2020-03-08 01:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0017_auto_20200308_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbaseinfo',
            name='smallurl',
            field=stdimage.models.StdImageField(blank=True, default='', upload_to='ProductPreViewPic', verbose_name='商品展示缩略图'),
        ),
    ]
