# Generated by Django 2.2.7 on 2020-03-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0018_auto_20200308_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '活动信息管理', 'verbose_name_plural': '活动信息管理'},
        ),
        migrations.AlterModelOptions(
            name='activityimage',
            options={'verbose_name': '活动图片', 'verbose_name_plural': '活动图片'},
        ),
        migrations.AlterModelOptions(
            name='activitytext',
            options={'verbose_name': '活动文本', 'verbose_name_plural': '活动文本'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': '活动类型管理', 'verbose_name_plural': '活动类型管理'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': '报名信息查看', 'verbose_name_plural': '报名信息查看'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '门店信息管理', 'verbose_name_plural': '门店信息管理'},
        ),
        migrations.AlterField(
            model_name='ptag',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='wechatapp.ProductBaseInfo', verbose_name='标注商品'),
        ),
    ]
