# Generated by Django 2.2.7 on 2020-03-08 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0021_auto_20200308_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptype',
            name='image',
        ),
        migrations.AddField(
            model_name='ptypeimage',
            name='ptype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_image', to='wechatapp.PType', verbose_name='商品类型'),
        ),
    ]
