# Generated by Django 2.2.7 on 2020-03-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0022_auto_20200308_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptype',
            old_name='activity_create_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='ptype',
            old_name='activity_operate_time',
            new_name='operate_time',
        ),
        migrations.AlterField(
            model_name='ptype',
            name='desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='描述'),
        ),
    ]
