# Generated by Django 2.2.7 on 2020-03-08 03:24

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0023_auto_20200308_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptype',
            name='desc',
            field=models.IntegerField(blank=True, choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], verbose_name='属性'),
        ),
        migrations.AlterField(
            model_name='ptypeimage',
            name='image',
            field=stdimage.models.StdImageField(default='', upload_to='PTypeImage', verbose_name='商品类型图片'),
        ),
    ]
