# Generated by Django 2.2.7 on 2020-03-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0026_auto_20200308_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PTypeImage',
        ),
    ]
