# Generated by Django 2.2.7 on 2020-03-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0029_ptypeposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbaseinfo',
            name='productType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatapp.PType', verbose_name='商品分类'),
        ),
    ]
