# Generated by Django 2.2.7 on 2020-03-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0030_auto_20200308_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbaseinfo',
            name='productType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wechatapp.PType', verbose_name='商品分类'),
        ),
    ]
