# Generated by Django 2.2.7 on 2020-03-09 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0031_auto_20200308_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsecondcategory',
            name='typeName',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='productbaseinfo',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='typeChildName',
        ),
        migrations.AlterModelOptions(
            name='producturl',
            options={'verbose_name': '商品详情图片', 'verbose_name_plural': '商品详情图片管理'},
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='productType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='wechatapp.PType', verbose_name='商品分类'),
        ),
        migrations.DeleteModel(
            name='ProductMainCategory',
        ),
        migrations.DeleteModel(
            name='ProductSecondCategory',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
