# Generated by Django 2.2.7 on 2020-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0032_auto_20200309_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbaseinfo',
            name='barCode',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='条形编码'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='norms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='systemCode',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='系统编码'),
        ),
        migrations.AlterField(
            model_name='productbaseinfo',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='重量'),
        ),
    ]
