# Generated by Django 2.2.7 on 2020-03-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechatapp', '0013_auto_20200309_1805'),
        ('wechatapp', '0033_auto_20200309_1713'),
    ]

    operations = [
    ]
